---
title: "About"
---

This is a "papers with code" website for "Using iNaturalist to understand trait and climate drivers of daily activity patterns in temperate butterflies" in prep.

## Intro

Animals are expected to optimize the times that they are active to maximize their fitness in the face of constraints of light availability, temperature, competition, and predation pressure. It is difficult to impossible to obtain data on activity regimes with spatial, temporal, and taxonomic breath. This project grapples with the distinctive biases of iNaturalist data to explore patterns and trade-offs of activity in butterflies.

## Questions

1.  Do butterflies species have different activity regimes/niches and if so what are they?
2.  When daylength is longer and temperature is hotter, do butterflies start their activity earlier in the day and end it later?
3.  Do smaller species have different activity regimes than larger species?
4.  Do species with a preference for open unshaded environments have different regimes?

## Predictions based on previous research

1.  Butterflies will start earlier and end later when days are longer and temperature is warmer
2.  Smaller species will forage less in the middle of the day because they are less able to dissipate heat, ESPECIALLY in hot environments
